#!/bin/bash

# gs options adapted from Mark Everitt's comment at
# https://bugs.launchpad.net/inkscape/+bug/199689/comments/4

while [[ "$1" != "" ]]; do
  OLDPDF="$1"
  shift
  NEWPDF="${OLDPDF%.pdf}.nofonts.pdf"
  gs -sDEVICE=pswrite -sOutputFile=- -q -dNOCACHE -dBATCH -dNOPAUSE "$OLDPDF" -c quit | ps2pdf - "$NEWPDF"
done
